input_dir: "/storage/research/ips_pal/GENOMICS/RAW/GENICA/Droc/A01975_441_A01975_432"
work_dir: "/storage/research/ips_pal/GENOMICS/WORK/GENICA/READ_CLEANING/Droc"

reference: "/storage/research/ips_pal/GENOMICS/REFERENCE_GENOMES/Dryas_octopetala_ncDNA.fna"

fastqc:
  outdir: "fastqc"   # relative to work_dir

adapters:
  a_3prime: "AGATCGGAAG"
  g_5prime_loop: "CTTCCGATCT"

cutadapt:
  threads: 4
  minlen: 30
  qual: 30
  error_rate: 1

loop_stop:
  max_hits: 100

adapterremoval:
  threads: 4
  minquality: 30
  minlength: 30

bbmap:
  xmx: "40g"

bwa:
  threads: 8
  aln_opts: "-l 1024 -n 0.01 -o 2"
