input_dir: "/storage/research/ips_pal/GENOMICS/RAW"
work_dir: "/storage/research/ips_pal/GENOMICS/WORK/GENICA/READS_TO_BAM/Droc"
metadata_to_run: "/storage/research/ips_pal/GENOMICS/WORK/GENICA/work_Ines/metadata/Metadata_Droc.txt2"
#Make sure the metadata to run the analysis contains
# id_code seq_id cal_age folder

reference: "/storage/research/ips_pal/GENOMICS/REFERENCE_GENOMES/SPECIES/Dryas_octopetala.fna"

organelle_contigs:
  - OY992841.1
  - OY992842.1
  - OY992843.1

adapters:
  a_3prime: "AGATCGGAAG"
  g_5prime_loop: "CTTCCGATCT"

cutadapt:
  threads: 4
  minlen: 30
  qual: 30
  error_rate: 1

loop_stop:
  max_hits: 100

adapterremoval:
  threads: 4
  minquality: 30
  minlength: 30

bbmap:
  xmx: "64g"

bwa:
  threads: 16
  aln_opts: "-l 1024 -n 0.01 -o 2"

samtools:
  filter_flag: 2052 # unmapped + supplementary
  mapq: 30
